### ISSUE TITLE
Is this the latest version?

### ISSUE THREAD

**Issue by wxnnvs** [Eaglercraft-Archive/eaglercraftx-1.8.8-source#1]
I had the eaglercraft source before, but it was u17 while the latest version of eaglercraft is u19.
Is this updated?

**Comment by radmanplays** [comment]
idk.
use these instead :
https://github.com/Eaglercraft-Archive/Eaglercraft-PBR-shaders
https://github.com/Eaglercraft-Archive/Eaglercraftx-u19-source
